kind: Ingress

metadata:
  name: nginx-ingress
  annotations:
    version: 0.0.11

spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /my-app
            backend:
              service:
                name: nginx
                port:
                  number: 80
