apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - argocd-svc.yaml

namespace: argocd

namePrefix: argocd-

commonLabels:
  environment: argocd

patchesStrategicMerge:
  - ingress.yaml
